name: Build
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform: ["0.12.29", "0.13.0"]
    container:
      image: hashicorp/jsii-terraform

    steps:
      - uses: actions/checkout@v2
      - name: installing dependencies
        run: |
          yarn install
      - name: compile
        run: |
          tools/align-version.sh
          yarn build
        env:
          TERRAFORM_BINARY_NAME: "terraform${{ matrix.terraform }}"
      - name: test
        run: |
          yarn test
        env:
          TERRAFORM_BINARY_NAME: "terraform${{ matrix.terraform }}"
      - name: create bundle
        run: yarn package
      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  linux_integration:
    runs_on: ubuntu-latest
    strategy:
      matrix:
        terraform: ["0.12.29", 0.13.0-rc1]
    container:
      image: hashicorp/jsii-terraform
    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: integration tests
        run: yarn integration
        env:
          TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
          TERRAFORM_BINARY_NAME: "terraform${{ matrix.terraform }}"

  windows_integration:
    runs_on: windows-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Download dist
        uses: actions/download-artifact@v2
          name: dist
      - name: integration tests
        run: yarn integration-windows
        env:
          TERRAFORM_CLOUD_TOKEN: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
