name: Examples Integration
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"

jobs:
  build-example-matrix:
    runs-on: ubuntu-latest
    outputs:
      examples: ${{ steps.set-example.outputs.examples }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: set-examples
        run: |
          examples=$(npx lerna list --scope "@examples/*")
          echo "::set-output name=examples::$examples"

  examples:
    needs: build-example-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform: ["0.15.4"]
        target: ${{fromJSON(needs.build-example-matrix.outputs.examples)}}
    container:
      image: docker.mirror.hashicorp.services/hashicorp/jsii-terraform
    env:
      TF_PLUGIN_CACHE_DIR: "/root/.terraform.d/plugin-cache"
      CHECKPOINT_DISABLE: "1"
    steps:
      - uses: actions/checkout@v2
      - name: installing dependencies
        run: |
          yarn install
      - name: compile
        run: |
          yarn build
        env:
          TERRAFORM_BINARY_NAME: "terraform${{ matrix.terraform }}"
      - name: create bundle
        run: yarn package
      - name: bootstrap plugin cache
        run: yum install -y jq && yarn bootstrap-plugin-cache
        env:
          TERRAFORM_BINARY_NAME: "terraform${{ matrix.terraform }}"
      - name: examples integration tests
        run: test/run-against-dist tools/build-examples.sh ${TEST_TARGET}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          TEST_TARGET: "${{ matrix.target }}"
          TERRAFORM_BINARY_NAME: "terraform${{ matrix.terraform }}"
          MAVEN_OPTS: "-Xmx3G"
